### ISSUE TITLE
network interruption error (during registration) 

### ISSUE THREAD

**Issue by manuelsprung** [HADatAc/sir#27]
![Screenshot 2023-08-31 at 1 19 19 PM](https://github.com/HADatAc/sir/assets/138029768/99286170-f226-4747-b62f-48c5c3b3791e)
I encountered a network interruption error (see attached screenshot) during registration of new questionnaire in my contributor account msprung

**Comment by paulopinheiro1234** [comment]
That is a problem with Pantheon. You need to report this issue with UCLA's IT and see what they report. I will close this specific issue.
